name: roofa
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  # Packges Will i used in the app
  google_fonts: ^2.2.0
  pin_code_fields: ^7.3.0
  get: ^4.6.1 # State Mangament
  flutter_svg:
  flutter_screenutil: 5.0.1
  date_time_picker: 2.0.0
  intl:
  flutter_rating_bar: ^4.0.0
  select_dialog: ^2.0.0
  flutter_slidable: ^1.2.0
  intl_phone_field: ^3.1.0
  charts_flutter:
  firebase_auth:
  firebase_core:
  firebase:
  firebase_storage:
  firebase_database:
  firebase_core_web:
  cloud_firestore:
  url_launcher:
  image_picker:
  file_picker:
  firebase_analytics:
  open_file:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0


flutter:

  uses-material-design: true

  assets:
    - images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
